### ISSUE TITLE
Add tartu?

### ISSUE THREAD

**Issue by Flypaste** [Enbayft/Observation-on-BB-Gun#1]
Tartu is missing from eHP/DPS sheet, I tried adding her myself to my sheet but couldn't make it work cause my brain too smooth

**Comment by Enbayft** [comment]
> Tartu is missing from eHP/DPS sheet, I tried adding her myself to my sheet but couldn't make it work cause my brain too smooth

Sorry for the late reply! I'm not sure why Tartu isn't in the sheets, but I added her in. Thanks for letting me know.
